# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'my_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1022, 623)
        font = QtGui.QFont()
        font.setFamily("隶书")
        font.setPointSize(9)
        MainWindow.setFont(font)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon = QtGui.QIcon.fromTheme("my")
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.text = QtWidgets.QTextBrowser(self.centralwidget)
        self.text.setGeometry(QtCore.QRect(700, 50, 281, 511))
        font = QtGui.QFont()
        font.setFamily("隶书")
        font.setPointSize(12)
        self.text.setFont(font)
        self.text.setTabStopWidth(80)
        self.text.setObjectName("text")
        self.load_data = QtWidgets.QPushButton(self.centralwidget)
        self.load_data.setGeometry(QtCore.QRect(20, 10, 93, 28))
        self.load_data.setObjectName("load_data")
        self.gui = QtWidgets.QGraphicsView(self.centralwidget)
        self.gui.setGeometry(QtCore.QRect(20, 50, 661, 511))
        self.gui.setObjectName("gui")
        self.pic = QtWidgets.QPushButton(self.centralwidget)
        self.pic.setGeometry(QtCore.QRect(120, 10, 93, 28))
        self.pic.setObjectName("pic")
        self.mean = QtWidgets.QPushButton(self.centralwidget)
        self.mean.setGeometry(QtCore.QRect(230, 10, 93, 28))
        self.mean.setObjectName("mean")
        self.mean_img = QtWidgets.QPushButton(self.centralwidget)
        self.mean_img.setGeometry(QtCore.QRect(340, 10, 131, 28))
        self.mean_img.setObjectName("mean_img")
        self.feature = QtWidgets.QPushButton(self.centralwidget)
        self.feature.setGeometry(QtCore.QRect(480, 10, 93, 28))
        self.feature.setObjectName("feature")
        self.value = QtWidgets.QPushButton(self.centralwidget)
        self.value.setGeometry(QtCore.QRect(590, 10, 93, 28))
        self.value.setObjectName("value")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1022, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.show_load = QtWidgets.QAction(MainWindow)
        self.show_load.setCheckable(True)
        self.show_load.setChecked(False)
        self.show_load.setEnabled(True)
        self.show_load.setObjectName("show_load")
        self.p2_1 = QtWidgets.QAction(MainWindow)
        self.p2_1.setObjectName("p2_1")
        self.p2_2 = QtWidgets.QAction(MainWindow)
        self.p2_2.setObjectName("p2_2")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "特征脸系统"))
        self.load_data.setText(_translate("MainWindow", "数据加载"))
        self.pic.setText(_translate("MainWindow", "PCA"))
        self.mean.setText(_translate("MainWindow", "平均人脸"))
        self.mean_img.setText(_translate("MainWindow", "中心化结果"))
        self.feature.setText(_translate("MainWindow", "特征脸"))
        self.value.setText(_translate("MainWindow", "特征值"))
        self.show_load.setText(_translate("MainWindow", "show data"))
        self.p2_1.setText(_translate("MainWindow", "print2-1"))
        self.p2_2.setText(_translate("MainWindow", "print2-2"))
